id: IF1FC8C7F
legacy_id: P004601
ocr_import_info:
  bdrc_scan_id: W27212
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T02:22:53'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:54:46.201849+00:00'
last_modified: 2022-09-02 14:55:29.884939
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27212
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW27212
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ངག་དབང་ཚུལ་ཁྲིམས་དཔལ་བཟང་པོའི་སྐྱེས་རབས་རྣམ་ཐར་དད་པའི་སྒོ་འབྱེད།
  author: སྤང་ལུང ༠༡་བློ་བཟང་ཐུགས་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.5852575084390224
  ocr_word_median_confidence_index: 0.6100000143051147
quality: null
bases:
  I1CZ1933:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1933
      total_pages: 1261
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1933.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.5852575084390224
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
