id: IF1FC8C7F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T02:30:47+00:00'
last_modified: '2022-06-08T02:14:02.784607+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27212
  title: ངག་དབང་ཚུལ་ཁྲིམས་དཔལ་བཟང་པོའི་སྐྱེས་རབས་རྣམ་ཐར་དད་པའི་སྒོ་འབྱེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EEDA:
      image_group_id: I1CZ1933
      title: ''
      total_pages: 1261
      order: 1
      base_file: EEDA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
