id: P004601
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 11:43:49.414357
source_metadata:
  id: bdr:W27212
  title: ངག་དབང་ཚུལ་ཁྲིམས་དཔལ་བཟང་པོའི་སྐྱེས་རབས་རྣམ་ཐར་དད་པའི་སྒོ་འབྱེད
  author: ''
  volumes:
    4f78a97abb8f40bfb90dfcc1b6887644:
      image_group_id: I1CZ1933
      title: ''
      volume_number: 1
      total_pages: 1261
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
