id: P004601
initial_creation_type: ocr
source_metadata:
  id: bdr:W27212
  title: ངག་དབང་ཚུལ་ཁྲིམས་དཔལ་བཟང་པོའི་སྐྱེས་རབས་རྣམ་ཐར་དད་པའི་སྒོ་འབྱེད
  author: ''
  volumes:
    4f78a97abb8f40bfb90dfcc1b6887644:
      image_group_id: I1CZ1933
      title: ''
      volume_number: 1
      total_pages: 1261
